exclude :test_a_call, "ArgumentError: unknown event: a_call"
exclude :test_a_return, "ArgumentError: unknown event: a_return"
exclude :test_aliased_c_method, "ArgumentError: unknown event: call"
exclude :test_aliased_ruby_method, "ArgumentError: unknown event: call"
exclude :test_allow_reentry, "NoMethodError: undefined method `allow_reentry' for TracePoint:Class"
exclude :test_argument_error_on_bmethod, "ArgumentError: unknown event: a_call"
exclude :test_b_call_with_redo, "ArgumentError: unknown event: a_call"
exclude :test_b_tracepoints_going_away, "ArgumentError: unknown event: call"
exclude :test_break, "spurious; <[\"c-return\", 1, :set_trace_func, Kernel]> expected but was nil."
exclude :test_break_with_rescue, "ArgumentError: unknown event: return"
exclude :test_c_call, "<[\"c-return\", 1, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_c_call_aliased_method, "ArgumentError: unknown event: c_call"
exclude :test_c_call_no_binding, "ArgumentError: unknown event: c_call"
exclude :test_c_call_removed_method, "ArgumentError: unknown event: c_call"
exclude :test_c_return_no_binding, "ArgumentError: unknown event: c_return"
exclude :test_call, "<[\"c-return\", 1, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_class, "<[\"c-return\", 1, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_const_missing, "ArgumentError: unknown event: c_call"
exclude :test_define_method_on_exception, "ArgumentError: unknown event: call"
exclude :test_define_method_on_return, "ArgumentError: unknown event: call"
exclude :test_enable_target_thread, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_fiber_switch, "ArgumentError: unknown event: fiber_switch"
exclude :test_lineno_in_optimized_insn, "<15> expected but was <nil>."
exclude :test_method_missing, "ArgumentError: unknown event: c_call"
exclude :test_multiple_enable, "ArgumentError: unknown event: call"
exclude :test_multiple_tracepoints_same_bmethod, "ArgumentError: unknown event: return"
exclude :test_non_local_return_across_multiple_define_methods, "ArgumentError: unknown event: return"
exclude :test_raise, "<[\"c-return\", 1, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_rb_rescue, "ArgumentError: unknown event: a_call"
exclude :test_recursive, "| <internal:core> core/tracepoint.rb:24:in `block in initialize': unknown event: c_call (ArgumentError)"
exclude :test_remove_in_trace, "transient: [ruby-dev:42350]. <#<TestSetTraceFunc:...> expected but was <false>"
exclude :test_rescue_and_ensure_should_not_cause_b_return, "ArgumentError: unknown event: a_call"
exclude :test_return, "<[\"c-return\", 1, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_return2, "<[\"c-return\", 1, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_return_bmethod_location, "ArgumentError: unknown event: return"
exclude :test_return_event_with_rescue, "ArgumentError: unknown event: return"
exclude :test_return_value_with_rescue, "ArgumentError: unknown event: return"
exclude :test_return_value_with_rescue_and_defined_methods, "ArgumentError: unknown event: return"
exclude :test_script_compiled, "ArgumentError: unknown event: script_compiled"
exclude :test_set_trace_func, "NoMethodError: undefined method `[]' for nil:NilClass"
exclude :test_single_raise_inside_load, "NameError: uninitialized constant TestSetTraceFunc::FileUtils"
exclude :test_stat_exists, "NoMethodError: undefined method `stat' for TracePoint:Class"
exclude :test_target_different_bmethod_same_iseq, "ArgumentError: unknown event: call"
exclude :test_thread_add_trace_func, "hangs"
exclude :test_thread_trace, "NoMethodError: private method `set_trace_func' called for #<Thread:0x918>"
exclude :test_throwing_return_with_finish_frame, "ArgumentError: unknown event: call"
exclude :test_tp_rescue, "<[]> expected but was <[688,"
exclude :test_tp_rescue_event, "ArgumentError: unknown event: rescue"
exclude :test_trace_defined_method, "<[\"c-return\", 3, :set_trace_func, Kernel]> expected but was <nil>."
exclude :test_trace_point_at_return_when_exception, "[TestSetTraceFunc::FOO_ERROR] exception expected, not #<TestSetTraceFunc::BAR_ERROR: TestSetTraceFunc::BAR_ERROR>."
exclude :test_trace_point_binding_after_break, "| <internal:core> core/tracepoint.rb:24:in `block in initialize': unknown event: c_return (ArgumentError)"
exclude :test_trace_point_binding_in_ifunc, "ArgumentError: unknown event: raise"
exclude :test_tracepoint, "ArgumentError: unknown event: end"
exclude :test_tracepoint_access_from_outside, "[RuntimeError] exception expected, not #<NoMethodError: undefined method `defined_class' for #<TracePoint:disabled>>."
exclude :test_tracepoint_attr, "ArgumentError: unknown event: c_call"
exclude :test_tracepoint_b_return_with_lambda, "ArgumentError: unknown event: b_return"
exclude :test_tracepoint_b_return_with_next, "ArgumentError: unknown event: b_return"
exclude :test_tracepoint_block, "ArgumentError: unknown event: call"
exclude :test_tracepoint_callee_id, "ArgumentError: unknown event: raise"
exclude :test_tracepoint_disable, "ArgumentError: unknown event: call"
exclude :test_tracepoint_enable, "ArgumentError: unknown event: call"
exclude :test_tracepoint_enable_target, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_tracepoint_enable_with_target_line, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_tracepoint_enable_with_target_line_two_times, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_tracepoint_enabled, "ArgumentError: unknown event: call"
exclude :test_tracepoint_inspect, "Expected / in / to match \"#<TracePoint:line /b/b/e/main/test/mri/tests/ruby/test_settracefunc.rb:1116>\"."
exclude :test_tracepoint_nested_enabled_with_target, "<\"can't nest-enable a targeting TracePoint\"> expected but was <\"wrong number of arguments (given 1, expected 0)\">."
exclude :test_tracepoint_opt_invokebuiltin_delegate_leave, "Expected /^0000 opt_invokebuiltin_delegate_leave / to match \"\"."
exclude :test_tracepoint_parameters, "ArgumentError: unknown event: end"
exclude :test_tracepoint_raised_exception, "ArgumentError: unknown event: call"
exclude :test_tracepoint_return_value, "ArgumentError: unknown event: call"
exclude :test_tracepoint_struct, "ArgumentError: unknown event: c_call"
exclude :test_tracepoint_thread, "ArgumentError: unknown event: thread_begin"
exclude :test_tracepoint_thread_begin, "ArgumentError: unknown event: thread_begin"
exclude :test_tracepoint_thread_end, "ArgumentError: unknown event: thread_end"
exclude :test_tracepoint_thread_end_with_exception, "ArgumentError: unknown event: thread_end"
exclude :test_while_in_while, "Bug #17868."
